image: icecubetray/alpine-icy:latest


stages:
  - prepare
  - build
  - test




.build_template: &build_template
  stage: build
  script:
    - alpine-icy-info color
    - echo "Profile ${PROFILE} will be built using ${CC}."
    - make clean CFLAGS_EXTRA="-DLSCST_SALSA20_FULL=1" PROFILE="$PROFILE" CC="$CC" libserum install
    - make clean PROFILE="$PROFILE" CC="$CC" test
    - mkdir bin/$PROFILE
    - mv /usr/lib/libserum.so bin/$PROFILE/libserum.so
    - mv bin/test bin/$PROFILE/test
  artifacts:
    paths:
      - bin/$PROFILE/libserum.so
      - bin/$PROFILE/test
      - sbin/test-*.sh
      - test/siot/*.txt


.test_template: &test_template
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Testing profile ${PROFILE}."
    - mv bin/$PROFILE/libserum.so /usr/lib/libserum.so
    - sbin/test-siot.sh "bin/$PROFILE/test"
    - bin/$PROFILE/test unit-test
    - bin/$PROFILE/test run-cst




prepare:
  stage: prepare
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - .make
      - sbin/test-*.sh
      - test/siot/*.txt
  script:
    - echo Preparing to build.


build-debug:
  <<: *build_template
  variables:
    PROFILE: debug
    CC: gcc

build-debug-cst:
  <<: *build_template
  variables:
    PROFILE: debug-cst
    CC: gcc

build-release:
  <<: *build_template
  variables:
    PROFILE: release
    CC: gcc

build-release-cst:
  <<: *build_template
  variables:
    PROFILE: release-cst
    CC: gcc


test-debug:
  <<: *test_template
  variables:
    PROFILE: debug

test-debug-cst:
  <<: *test_template
  variables:
    PROFILE: debug-cst

test-release:
  <<: *test_template
  variables:
    PROFILE: release

test-release-cst:
  <<: *test_template
  variables:
    PROFILE: release-cst
