image: icecubetray/alpine-icy:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - make clean release install
    - make clean bin/test
    - mv /usr/lib/libserum.so bin/libserum.so
  artifacts:
    paths:
      - bin/libserum.so
      - bin/test

test:
  stage: test
  script:
    - mv bin/libserum.so /usr/lib/libserum.so
    - bin/test
