image: icecubetray/alpine-icy:latest

stages:
  - build
  - test

build:
  stage: build
  variables:
    PROFILE: release-cst
    CC: gcc
  script:
    - alpine-icy-info color
    - make clean CFLAGS_EXTRA="-DLSCST_SALSA20_FULL=1" PROFILE="$PROFILE" CC="$CC" all install
    - make clean PROFILE="$PROFILE" CC="$CC" bin/test
    - mv /usr/lib/libserum.so bin/libserum.so
  artifacts:
    paths:
      - bin/libserum.so
      - bin/test

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - mv bin/libserum.so /usr/lib/libserum.so
    - bin/test
