image: icecubetray/alpine-icy:latest

stages:
  - build
  - test

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PROFILE: debug-cst
    CC: gcc
  script:
    - alpine-icy-info color
    - make clean CFLAGS_EXTRA="-DLSCST_SALSA20_FULL=1" PROFILE="$PROFILE" CC="$CC" libserum install
    - make clean PROFILE="$PROFILE" CC="$CC" test
    - mv /usr/lib/libserum.so bin/libserum.so
  artifacts:
    paths:
      - bin/libserum.so
      - bin/test
      - sbin/test-*.sh
      - test/siot/*.txt

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - mv bin/libserum.so /usr/lib/libserum.so
    - bin/test run-cst
    - sbin/test-siot.sh
