sudo: required

language: c

services:
  - docker

env:
  - REPO="$TRAVIS_REPO_SLUG" REPODIR="/repositories/$REPO" BRANCH="$TRAVIS_BRANCH"

before_install:
  - docker pull icecubetray/alpine-icy:latest

install:
  - docker run -v "$(pwd)":"$REPODIR" -itd --name alpine-icy icecubetray/alpine-icy

after_install:
  - docker exec alpine-icy sh -c "cd '$REPODIR' && pwd && make clean release install bin/test"

script:
  - docker exec alpine-icy sh -c "cd '$REPODIR' && pwd && make test"

after_script:
  - docker container rm --force alpine-icy
