language: c




sudo: required

os:
  - linux

env:
  - CC=gcc PROFILE=debug
  - CC=gcc PROFILE=debug-cst
  - CC=gcc PROFILE=release
  - CC=gcc PROFILE=release-cst




before_install:
  - make PROFILE="$PROFILE" CC="$CC" make-debug

install:
  - make clean PROFILE="$PROFILE" CC="$CC" libserum
  - sudo make install


before_script:
  - make clean PROFILE="$PROFILE" CC="$CC" test

script:
  - bin/test run-cst
